build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related prod webhook hookdeck Apis"
  contactDetails:
    name: "Reine-Aishwarya Product Owner"
    email: "{cipher}b50bcb2faf39c0302484bcf6479c58fd6e94c0a210b6a09ef1b4c650bac3baf6be1bbc9c3b8e2d92dad40fba9a276e3f"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
