build:
  version: "3.0"

cards:
  message: "Welcome to eazybank cards related local Apis"
  contactDetails:
    name: "Dragos-Leach Developer"
    email: "dragos@mygithub.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932

